# Generated by Django 2.2.16 on 2020-11-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='n/a')),
                ('password', models.TextField(default='n/a')),
                ('mobile_no', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('auth', models.TextField(default='n/a')),
            ],
        ),
    ]
