# Generated by Django 2.2.16 on 2020-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='session_key',
            field=models.TextField(default='n/a'),
        ),
    ]
