# Generated by Django 2.2.16 on 2020-11-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(default='n/a')),
                ('reciever', models.TextField(default='n/a')),
                ('message', models.TextField(default='n/a')),
                ('date', models.TextField(default='n/a')),
                ('time', models.TextField(default='n/a')),
            ],
        ),
    ]
