# Generated by Django 2.2.16 on 2020-11-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages_model',
            old_name='reciever',
            new_name='rx',
        ),
    ]
